/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionStatus = "PENDING" | "SUBMITTED" | "CONFIRMED" | "FAILED";

export const TransactionStatus = {
    Pending: "PENDING",
    Submitted: "SUBMITTED",
    Confirmed: "CONFIRMED",
    Failed: "FAILED",
} as const;
