/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface Transaction {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    chainId: number;
    projectId: string;
    fromAddress: string;
    toAddress: string;
    amount: string;
    hash: string;
    signedTxn: string;
    block: number;
    status: Syndicate.funding.TransactionStatus;
}
