/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface TransactionsByProjectResponse {
    transactions: Syndicate.funding.Transaction[];
    total: number;
}
