/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const TransactionStatus: core.serialization.Schema<
    serializers.funding.TransactionStatus.Raw,
    Syndicate.funding.TransactionStatus
> = core.serialization.enum_(["PENDING", "SUBMITTED", "CONFIRMED", "FAILED"]);

export declare namespace TransactionStatus {
    type Raw = "PENDING" | "SUBMITTED" | "CONFIRMED" | "FAILED";
}
