/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const TransactionsByProjectResponse: core.serialization.ObjectSchema<
    serializers.funding.TransactionsByProjectResponse.Raw,
    Syndicate.funding.TransactionsByProjectResponse
> = core.serialization.object({
    transactions: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).funding.Transaction)
    ),
    total: core.serialization.number(),
});

export declare namespace TransactionsByProjectResponse {
    interface Raw {
        transactions: serializers.funding.Transaction.Raw[];
        total: number;
    }
}
