/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetRequestsByProjectIdRequest {
    /**
     * Optional search parameter will filter by function signature, contract address, or transaction id
     */
    search?: string;
    page?: number;
    limit?: number;
    invalid?: boolean;
}
