/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../../..";

export interface GetTransactionsByProjectIdRequest {
    search?: string;
    page?: number;
    limit?: number;
    reverted?: boolean;
    status?: Syndicate.wallet.TransactionStatus | Syndicate.wallet.TransactionStatus[];
}
