/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetWalletsByProjectIdRequest {
    /**
     * Optional parameter to return this address's balance and total count of confirmed transactions
     */
    withData?: boolean;
}
