/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const CreateWalletErrorBody: core.serialization.ObjectSchema<
    serializers.wallet.CreateWalletErrorBody.Raw,
    Syndicate.wallet.CreateWalletErrorBody
> = core.serialization.object({
    projectId: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace CreateWalletErrorBody {
    interface Raw {
        projectId: string;
        message: string;
    }
}
