/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const CreateWalletRequest: core.serialization.ObjectSchema<
    serializers.wallet.CreateWalletRequest.Raw,
    Syndicate.wallet.CreateWalletRequest
> = core.serialization.object({
    projectId: core.serialization.string(),
    chainId: core.serialization.number(),
    type: core.serialization.lazy(async () => (await import("../../..")).wallet.WalletType).optional(),
});

export declare namespace CreateWalletRequest {
    interface Raw {
        projectId: string;
        chainId: number;
        type?: serializers.wallet.WalletType.Raw | null;
    }
}
