/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const ProjectTransactionStatsResponse: core.serialization.ObjectSchema<
    serializers.wallet.ProjectTransactionStatsResponse.Raw,
    Syndicate.wallet.ProjectTransactionStatsResponse
> = core.serialization.object({
    numberOfConfirmedTransactions: core.serialization.number(),
    numberOfSubmittedTransactions: core.serialization.number(),
    numberOfPendingTransactions: core.serialization.number(),
    numberOfFailedTransactions: core.serialization.number(),
});

export declare namespace ProjectTransactionStatsResponse {
    interface Raw {
        numberOfConfirmedTransactions: number;
        numberOfSubmittedTransactions: number;
        numberOfPendingTransactions: number;
        numberOfFailedTransactions: number;
    }
}
