/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const RetireWalletRequest: core.serialization.ObjectSchema<
    serializers.wallet.RetireWalletRequest.Raw,
    Syndicate.wallet.RetireWalletRequest
> = core.serialization.object({
    projectId: core.serialization.string(),
    walletAddress: core.serialization.string(),
    gasRecipient: core.serialization.string().optional(),
});

export declare namespace RetireWalletRequest {
    interface Raw {
        projectId: string;
        walletAddress: string;
        gasRecipient?: string | null;
    }
}
