/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const TransactionsByProjectResponse: core.serialization.ObjectSchema<
    serializers.wallet.TransactionsByProjectResponse.Raw,
    Syndicate.wallet.TransactionsByProjectResponse
> = core.serialization.object({
    transactionAttempts: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).wallet.TransactionAttempt)
    ),
    total: core.serialization.number(),
});

export declare namespace TransactionsByProjectResponse {
    interface Raw {
        transactionAttempts: serializers.wallet.TransactionAttempt.Raw[];
        total: number;
    }
}
