/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const TransactionRequestsByProjectResponse: core.serialization.ObjectSchema<
    serializers.wallet.TransactionRequestsByProjectResponse.Raw,
    Syndicate.wallet.TransactionRequestsByProjectResponse
> = core.serialization.object({
    transactionRequests: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).wallet.TransactionResponse)
    ),
    total: core.serialization.number(),
});

export declare namespace TransactionRequestsByProjectResponse {
    interface Raw {
        transactionRequests: serializers.wallet.TransactionResponse.Raw[];
        total: number;
    }
}
