/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const WalletType: core.serialization.Schema<serializers.wallet.WalletType.Raw, Syndicate.wallet.WalletType> =
    core.serialization.enum_(["BROADCAST", "SIGNING", "CLUSTER_MANAGER"]);

export declare namespace WalletType {
    type Raw = "BROADCAST" | "SIGNING" | "CLUSTER_MANAGER";
}
