/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SendTransactionRequest {
    /** (Optional) ID of the request. Needs to be a valid UUID. If provided, it will be saved and returned as the transactionId of the response. If not provided, we will generate one for you and return it as the transactionId. */
    requestId?: string;
    /** ID of the project you want this request to be sent from */
    projectId: string;
    /** The contract address to send request to */
    contractAddress: string;
    /** The chain ID for the network (e.g. 1 for Ethereum Mainnet, 137 for Polygon Mainnet, 80001 for Polygon Mumbai). For a complete list of chain IDs, see [ChainList](https://chainlist.org/?search=&testnets=true). */
    chainId: number;
    /** The human readable signature to call on the contract */
    functionSignature: string;
    /** (Optional) The function arguments for the transaction if any. The keys are the argument names or index from the provided function signature and the values are the argument values. */
    args?: Record<string, unknown>;
    organizationId: string;
    organizationTier: string;
}
