/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const ErrorBody: core.serialization.ObjectSchema<
    serializers.transact.ErrorBody.Raw,
    Syndicate.transact.ErrorBody
> = core.serialization.object({
    message: core.serialization.string(),
});

export declare namespace ErrorBody {
    interface Raw {
        message: string;
    }
}
