/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Syndicate from "../../../../api";
import * as core from "../../../../core";

export const ErrorWithMessage: core.serialization.ObjectSchema<
    serializers.transact.ErrorWithMessage.Raw,
    Syndicate.transact.ErrorWithMessage
> = core.serialization.object({
    message: core.serialization.string(),
});

export declare namespace ErrorWithMessage {
    interface Raw {
        message: string;
    }
}
