/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface CreateWalletRequest {
    projectId: string;
    chainId: number;
    type?: Syndicate.wallet.WalletType;
}
