/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProjectTransactionStatsResponse {
    numberOfConfirmedTransactions: number;
    numberOfSubmittedTransactions: number;
    numberOfPendingTransactions: number;
    numberOfFailedTransactions: number;
}
