/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProjectTransactionStatsResponse {
    numberOfTransactions: number;
    numberOfFailedTransactions: number;
}
