/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface TransactionResponse {
    transactionId: string;
    chainId: number;
    projectId: string;
    invalid: boolean;
    contractAddress: string;
    functionSignature: string;
    /** ABI encoded representation of the function name and parameters passed as input */
    data: string;
    /** Decoded function arguments passed as input to the contract's function identified by 'functionSignature' */
    decodedData?: Record<string, unknown>;
    value: string;
    createdAt: Date;
    updatedAt: Date;
    transactionAttempts?: Syndicate.wallet.TransactionAttempt[];
}
