/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface TransactionsByProjectResponse {
    transactionAttempts: Syndicate.wallet.TransactionAttempt[];
    total: number;
}
