/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface TransactionResponse {
    transactionId: string;
    chainId: number;
    projectId: string;
    invalid: boolean;
    contractAddress: string;
    functionSignature: string;
    data: string;
    value: string;
    createdAt: Date;
    updatedAt: Date;
    transactionAttempts?: Syndicate.wallet.TransactionAttempt[];
}
