/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface TransactionRequestsByProjectResponse {
    transactionRequests: Syndicate.wallet.TransactionResponse[];
    total: number;
}
