/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface TransactionAttempt {
    transactionId: string;
    hash: string;
    chainId: number;
    status: Syndicate.wallet.TransactionStatus;
    block: number;
    signedTxn: string;
    walletAddress: string;
    reverted: boolean;
    nonce: number;
    createdAt: Date;
    updatedAt: Date;
}
