/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionStatus = "PENDING" | "SUBMITTED" | "CONFIRMED";

export const TransactionStatus = {
    Pending: "PENDING",
    Submitted: "SUBMITTED",
    Confirmed: "CONFIRMED",
} as const;
