/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Syndicate from "../../..";

export interface WalletWithTxCountAndBalance extends Syndicate.wallet.Wallet {
    /** Number of confirmed transactions submitted by this address */
    txCount?: number;
    /** Balance in wei of this address's native gas token, as defined by chainId */
    balance?: string;
}
