/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Wallet {
    walletId: string;
    walletAddress: string;
    chainId: number;
    nonce: number;
    isActive: boolean;
    projectId: string;
    createdAt: Date;
    updatedAt: Date;
}
