/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WalletType = "BROADCAST" | "SIGNING" | "CLUSTER_MANAGER";

export const WalletType = {
    Broadcast: "BROADCAST",
    Signing: "SIGNING",
    ClusterManager: "CLUSTER_MANAGER",
} as const;
