/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as Syndicate from "../../..";

export class CreateWalletError extends errors.SyndicateError {
    constructor(body: Syndicate.wallet.CreateWalletErrorBody) {
        super({
            message: "CreateWalletError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, CreateWalletError.prototype);
    }
}
