/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class RetireWalletError extends errors.SyndicateError {
    constructor() {
        super({
            message: "RetireWalletError",
            statusCode: 500,
        });
        Object.setPrototypeOf(this, RetireWalletError.prototype);
    }
}
