/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class TransactionNotFoundError extends errors.SyndicateError {
    constructor() {
        super({
            statusCode: 404,
        });
        Object.setPrototypeOf(this, TransactionNotFoundError.prototype);
    }
}
