/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class WalletNotFoundError extends errors.SyndicateError {
    constructor() {
        super({
            message: "WalletNotFoundError",
            statusCode: 404,
        });
        Object.setPrototypeOf(this, WalletNotFoundError.prototype);
    }
}
