/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SyndicateEnvironment = {
    Production: "https://api.syndicate.io",
} as const;

export type SyndicateEnvironment = typeof SyndicateEnvironment.Production;
