/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class ImATeapotError extends errors.SyndicateError {
    constructor() {
        super({
            statusCode: 418,
        });
        Object.setPrototypeOf(this, ImATeapotError.prototype);
    }
}
