/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class InternalError extends errors.SyndicateError {
    constructor() {
        super({
            message: "InternalError",
            statusCode: 500,
        });
        Object.setPrototypeOf(this, InternalError.prototype);
    }
}
