/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as Syndicate from "../../..";

export class InvalidRequestIdError extends errors.SyndicateError {
    constructor(body: Syndicate.transact.ErrorBody) {
        super({
            message: "InvalidRequestIdError",
            statusCode: 422,
            body: body,
        });
        Object.setPrototypeOf(this, InvalidRequestIdError.prototype);
    }
}
