/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as Syndicate from "../../..";

export class MalformedFunctionDataError extends errors.SyndicateError {
    constructor(body: Syndicate.transact.ErrorWithMessage) {
        super({
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, MalformedFunctionDataError.prototype);
    }
}
